---
language: ruby
bundler_args: --without development system_tests
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.7.1"
    - PUPPET_GEM_VERSION="~> 4.0"  
matrix:
  fast_finish: true
notifications:
  email: false
